name: Daily MLB Props Update

on:
  schedule:
    - cron: '45 15 * * *'  # Runs daily at 11:45 AM EST / 3:45 PM UTC
  workflow_dispatch:       # Allows manual run from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily prop update
        run: python scripts/generate_ranked_props.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ranked_props.json
          git diff --cached --quiet || git commit -m "Daily update: Ranked props"
          git push
